# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   FortifyCLI:
    runs-on: windows-latest
    #needs: build

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 10.0

      - name: Setup Java
        uses: actions/setup-java@v1     # Required for ScanCentral Client and FoD Uploader
        with:
          java-version: 11

      - name: Download Fortify CLI
        run: |
          $filePath = "${{env.RUNNER_TEMP}}/fcli.jar"
          Invoke-WebRequest https://github.com/fortify-ps/fcli/releases/download/v1.2.0/fcli.jar -OutFile $filePath
          
      - name: FOD Session
        run: |
          java -jar ${{env.RUNNER_TEMP}}/fcli.jar fod session login --url ${{ secrets.FOD_API_URL }} --client-id=${{ secrets.FOD_API_KEY }} --client-secret=${{ secrets.FOD_API_SECRET }}

      - name: Create Release
        run: |
           java -jar ${{env.RUNNER_TEMP}}/fcli.jar fod release create --skip-if-exists --session="default" --sdlc-status="Development" -o="yaml" --output-to-file="app.yaml" --store="release" "FortifyCLI(Tre):1.5"
